#+SETUPFILE: setup.org
#+INCLUDE: header.org
#+TITLE: Preface

* Preface

Modern JavaScript lessons with practice exercises.

** Practical
These lessons are aimed at giving you practical skills to build real projects in JavaScript. In addition, the techniques covered here will enable you to adapt to other programming languages and styles. An important skill for any programmer is being able to *break problems down*. From lesson 04-Conditionals onwards, each lesson has many exercises (and solutions) for you to practice on to make sure you understand the concepts.

** Functional
Functional programming has a long history rooted in math developed in the 1930s. The values that functional programming brings to development have been realized and adopted to traditionally non-functional languages and frameworks, greatly accelerating in the recent years. As an example, [[https://reactjs.org/][React]], the most popular frontend library/framework (as of writing this), has changed from being object-oriented to functional. I personally find that functional programming is a lot of fun to learn and apply.

** Typed
JavaScript is known for having a messy and unintuitive type system. These lessons will teach you how to think about types in an intuitive way that will help you write clean and maintainable code. You will also be better prepared to learn other programming languages that will likely have stronger type systems or be statically typed, such as TypeScript, C, C++, Rust, Haskell, Elixir, etc.
